export const SERVICE_NAMES = {
  KIWIX: 'vanguard_relay_kiwix_server',
  OLLAMA: 'vanguard_relay_ollama',
  QDRANT: 'vanguard_relay_qdrant',
  CYBERCHEF: 'vanguard_relay_cyberchef',
  FLATNOTES: 'vanguard_relay_flatnotes',
  KOLIBRI: 'vanguard_relay_kolibri',
  KOLIBRI_GEN2: 'vanguard_relay_kolibri_2',
  // Supply Depot — curated catalog (ports 8400–8499)
  STIRLING_PDF: 'vanguard_relay_stirling_pdf',
  FILEBROWSER: 'vanguard_relay_filebrowser',
  CALIBREWEB: 'vanguard_relay_calibreweb',
  IT_TOOLS: 'vanguard_relay_it_tools',
  EXCALIDRAW: 'vanguard_relay_excalidraw',
  MESHTASTIC_WEB: 'vanguard_relay_meshtastic_web',
  MESHTASTICD: 'vanguard_relay_meshtasticd',
  MESHCORE_WEB: 'vanguard_relay_meshcore_web',
  HOMEBOX: 'vanguard_relay_homebox',
  VAULTWARDEN: 'vanguard_relay_vaultwarden',
  JELLYFIN: 'vanguard_relay_jellyfin',
}
